version: '3.3'
services:
    nifi:
        container_name: nifi
        image: apache/nifi:1.13.2
        user: root
        network_mode: bridge
        ports:
            - 8080:8080
            - 9998:9998